### Get current user using token
GET http://localhost:5104/api/Story/user
Authorization: Bearer {{access_token}}
 
### Story - get all 
GET http://localhost:5104/api/Story
Authorization: Bearer {{access_token}}

### Story - get by id
GET http://localhost:5104/api/Story/3
Authorization: Bearer {{access_token}}

### Story - generate
POST http://localhost:5104/api/Story/generate
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "preset": "fanatyk",
  "mainPrompt": "dupka",
  "promptParts": []
}

### Story - generate for free
POST http://localhost:5104/api/Story/generate?free=true
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "preset": "fanatyk",
  "mainPrompt": "dupka",
  "promptParts": []
}

### Story - presets
GET http://localhost:5104/api/Story/presets
